<?php
define( 'DP_INTRO_TOURS_DP_BUILD_TYPE', 'FREE' );
define( 'DP_INTRO_TOURS_ADMINATOR', '' );
define( 'DP_INTRO_TOURS_DP_DEBUG_EN', false );
define( 'DP_INTRO_TOURS_DP_ADMIN_DEBUG_EN', false );
define( 'DP_INTRO_TOURS_VERSION', '5.4.1' );
define( 'DP_INTRO_TOURS_NAME', 'Intro Tour Tutorial' );
define( 'DP_INTRO_TOURS_PREFIX', 'dp_intro_tours' );
define( 'DP_INTRO_TOURS_PRODUCT_UPDATE_KEY', '' );
define( 'DP_INTRO_TOURS_PRODUCT_ADMINATOR_END_POINT', '' );
define( 'DP_INTRO_TOURS_TRACKING_ENABLED', false );
define( 'DP_INTRO_TOURS_TRACKING_CLIENT_ID', 'o6grd4ebaw48kyeq' );
define( 'DP_INTRO_TOURS_TRACKING_CLIENT_SECRET', 'b2790943abafc48693d1c69b96dacdf8239af2b4' );
define( 'DP_INTRO_TOURS_PRODUCT_LINK_FREE', 'https://deeppresentation.com/plugins/dp-intro-tours' );
define( 'DP_INTRO_TOURS_PRODUCT_FEATURES_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_DEMO_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_KEY_BUY_LINK_FREE', '' );
define( 'DP_INTRO_TOURS_PRODUCT_ASK_FOR_RATING_LINK_FREE', 'https://wordpress.org/support/plugin/dp-intro-tours/reviews/' );
define( 'DP_INTRO_TOURS_PRODUCT_RATING_FEEDBACK_LINK_FREE', 'https://deeppresentation.com/wp-json/dp-feedback/dp-intro-tours/v1/' );
define( 'DP_INTRO_TOURS_PRODUCT_TITLE_FREE', 'Intro Tour Tutorial' );
define( 'DP_INTRO_TOURS_PRODUCT_LINK_PRO', 'https://deeppresentation.com/plugins/dp-intro-tours' );
define( 'DP_INTRO_TOURS_PRODUCT_FEATURES_LINK_PRO', 'https://deeppresentation.com/plugins/dp-intro-tours#pro-features' );
define( 'DP_INTRO_TOURS_PRODUCT_DEMO_LINK_PRO', 'https://demo.deeppresentation.com/' );
define( 'DP_INTRO_TOURS_PRODUCT_KEY_BUY_LINK_PRO', 'https://deeppresentation.com/product/intro-tour-tutorial-pro-plugin-for-wordpress/' );
define( 'DP_INTRO_TOURS_PRODUCT_ASK_FOR_RATING_LINK_PRO', 'https://deeppresentation.com/product/intro-tour-tutorial-pro-plugin-for-wordpress/#reviews' );
define( 'DP_INTRO_TOURS_PRODUCT_RATING_FEEDBACK_LINK_PRO', '' );
define( 'DP_INTRO_TOURS_PRODUCT_TITLE_PRO', 'Intro Tour Tutorial PRO' );
